services:
  database:
    image: postgres:16.3-alpine3.20
    container_name: tets-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-backend-payment-plugin
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
